name: Watch Image and Deploy

on:
  schedule:
    - cron: '0 */6 * * *' # Revisa cada 6 horas
  workflow_dispatch:      # Permite forzarlo manualmente
  push:
    branches:
      - main

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Latest Image Digest
        id: get_digest
        run: |
          TOKEN=$(curl -s "https://ghcr.io/token?scope=repository:viren070/aiostreams:pull" | jq -r .token)
          DIGEST=$(curl -s -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "https://ghcr.io/v2/viren070/aiostreams/manifests/latest" | jq -r '.config.digest')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Update Digest File
        id: update_repo
        run: |
          echo "${{ steps.get_digest.outputs.digest }}" > latest_digest.txt
          
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add latest_digest.txt
            git commit -m "Update image digest to ${{ steps.get_digest.outputs.digest }}"
            git push origin main
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install SSH Key
        if: steps.update_repo.outputs.changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BEAMUP_SSH_KEY }}
          known_hosts: 'placeholder'

      - name: Add Beamup to Known Hosts
        if: steps.update_repo.outputs.changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        run: ssh-keyscan a.baby-beamup.club >> ~/.ssh/known_hosts

      - name: Deploy to Beamup
        if: steps.update_repo.outputs.changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        run: |
          git remote add beamup dokku@a.baby-beamup.club:${{ secrets.BEAMUP_APP_NAME }}
          git push beamup main:master --force
